spring:
  datasource:
    url: jdbc:mysql://localhost:13306/consome?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: consome
    password: consome
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

logging:
  #level:
    #org.hibernate.SQL: debug

jwt:
  secret: "my-secret-key-for-dev-only-change-this-later"
  access-token-expiration: 3600000      # 1시간 (ms)
  refresh-token-expiration: 604800000   # 7일 (ms)